### ISSUE TITLE
Dockerfile Environment Variable Configuration Issue

### ISSUE THREAD

**Issue by DSamuelHodge** [delano/postman-mcp-server#8]
## Issue Description

The current Dockerfile has a hardcoded environment variable configuration that could cause issues with API key management and flexibility:

```dockerfile
# Current implementation
ENV POSTMAN_API_KEY=your_api_key_here
```

This approach has several problems:
1. It hardcodes the API key in the Dockerfile
2. Makes it difficult to update the key without rebuilding
3. Could lead to accidental key exposure in version control

## Proposed Solution

Update the Dockerfile to use environment variables more securely:

```dockerfile
# Modified implementation
ENV POSTMAN_API_KEY=${POSTMAN_API_KEY}
```

And use with docker-compose.yml or docker run with --env-file:

```yaml
# docker-compose.yml example
version: '3'
services:
  postman-mcp:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
```

This change would:
- Improve security by keeping sensitive data out of the Dockerfile
- Allow for easier key rotation
- Support different environments (dev, staging, prod)
- Follow Docker best practices for configuration

## Testing Done
- Verified working with Docker 24.0.7
- Tested with Postman API key injection
- Confirmed environment variable passing works correctly

Would you like me to prepare a PR with these changes?
